name: Endor SCA and Container Scanning
on:
  push:
    branches: [ main ]
    
jobs:
  build:
    permissions:
      security-events: write # Used to upload Sarif artifact to GitHub
      contents: read # Used to check out a private repository
      actions: read # Required for private repositories to upload Sarif files. GitHub Advanced Security licenses are required.
      id-token: write # Used for keyless authentication with Endor Labs
      issues: write # Required to automatically comment on PRs for new policy violations

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'microsoft'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Endor Scan
      uses: endorlabs/github-action@main
      with:
        namespace: 'arsalan-learn'
        scan_dependencies: true
        scan_secrets: true
        pr: false
        enable_github_action_token: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
        log_verbose: true
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}:your_tag
          
    - name: Scan container
      uses: endorlabs/github-action@main
      with:
        namespace: 'arsalan-learn'
        scan_secrets: false
        scan_dependencies: false
        scan_container: true
        pr: false
        enable_github_action_token: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
        log_verbose: true
        log_level: "info"
        project_name: "your_project_name"
        scan_summary_output_type: "table"
        image: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}:your_tag
